services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  s3:
    image: bitnami/minio:2024
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${S3_BUCKETS}
    volumes:
      - ./data/s3:/bitnami/minio/data
    ports:
      - 9000:9000
      - 9001:9001
