services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    user: '501:20'
  s3:
    image: bitnami/minio:2024
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${STORAGE_NAME}
    volumes:
      - ./data/s3:/bitnami/minio/data
    ports:
      - 9000:9000
      - 9001:9001
    user: '501:20'
