services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - db
    - s3
    restart: unless-stopped
    networks:
      - web
      - nginx
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - web
  s3:
    image: bitnami/minio:2024
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${STORAGE_NAME}
    volumes:
      - ./data/s3:/bitnami/minio/data
    networks:
      - web
networks:
  web:
    driver: bridge
  nginx:
    external: true
