const items = [
  {
    name: 'Laptop',
    photo_url: 'https://example.com/photos/laptop.jpg',
    status: 'Operational',
    quantity: 15,
    location: 'Storage Room A',
  },
  {
    name: 'Desktop PC',
    photo_url: 'https://example.com/photos/desktop_pc.jpg',
    status: 'Operational',
    quantity: 10,
    location: 'Workstation Area 1',
  },
  {
    name: 'Monitor',
    photo_url: 'https://example.com/photos/monitor.jpg',
    status: 'Operational',
    quantity: 20,
    location: 'Storage Room B',
  },
  {
    name: 'Keyboard',
    photo_url: 'https://example.com/photos/keyboard.jpg',
    status: 'Operational',
    quantity: 50,
    location: 'Storage Room A',
  },
  {
    name: 'Mouse',
    photo_url: 'https://example.com/photos/mouse.jpg',
    status: 'Operational',
    quantity: 50,
    location: 'Storage Room A',
  },
  {
    name: 'Router',
    photo_url: 'https://example.com/photos/router.jpg',
    status: 'Operational',
    quantity: 5,
    location: 'Networking Room',
  },
  {
    name: 'Ethernet Cable',
    photo_url: 'https://example.com/photos/ethernet_cable.jpg',
    status: 'Operational',
    quantity: 100,
    location: 'Networking Room',
  },
  {
    name: 'External Hard Drive',
    photo_url: 'https://example.com/photos/external_hard_drive.jpg',
    status: 'Operational',
    quantity: 25,
    location: 'Storage Room B',
  },
  {
    name: 'USB Flash Drive',
    photo_url: 'https://example.com/photos/usb_flash_drive.jpg',
    status: 'Operational',
    quantity: 75,
    location: 'Storage Room B',
  },
  {
    name: 'Power Supply Unit (PSU)',
    photo_url: 'https://example.com/photos/psu.jpg',
    status: 'Operational',
    quantity: 30,
    location: 'Storage Room C',
  },
  {
    name: 'Graphics Card',
    photo_url: 'https://example.com/photos/graphics_card.jpg',
    status: 'Operational',
    quantity: 12,
    location: 'Storage Room C',
  },
  {
    name: 'RAM Module',
    photo_url: 'https://example.com/photos/ram_module.jpg',
    status: 'Operational',
    quantity: 40,
    location: 'Storage Room C',
  },
  {
    name: 'Motherboard',
    photo_url: 'https://example.com/photos/motherboard.jpg',
    status: 'Operational',
    quantity: 10,
    location: 'Storage Room C',
  },
  {
    name: 'CPU',
    photo_url: 'https://example.com/photos/cpu.jpg',
    status: 'Operational',
    quantity: 10,
    location: 'Storage Room C',
  },
  {
    name: 'SSD',
    photo_url: 'https://example.com/photos/ssd.jpg',
    status: 'Operational',
    quantity: 20,
    location: 'Storage Room C',
  },
  {
    name: 'Network Switch',
    photo_url: 'https://example.com/photos/network_switch.jpg',
    status: 'Operational',
    quantity: 5,
    location: 'Networking Room',
  },
  {
    name: 'Soldering Iron',
    photo_url: 'https://example.com/photos/soldering_iron.jpg',
    status: 'Operational',
    quantity: 8,
    location: 'Repair Station',
  },
  {
    name: 'Multimeter',
    photo_url: 'https://example.com/photos/multimeter.jpg',
    status: 'Operational',
    quantity: 10,
    location: 'Repair Station',
  },
  {
    name: 'Screwdriver Set',
    photo_url: 'https://example.com/photos/screwdriver_set.jpg',
    status: 'Operational',
    quantity: 20,
    location: 'Toolbox 1',
  },
  {
    name: 'Anti-static Wrist Strap',
    photo_url: 'https://example.com/photos/anti_static_wrist_strap.jpg',
    status: 'Operational',
    quantity: 15,
    location: 'Toolbox 2',
  },
];

export { items };
