const memberMockData = [
  {
    id: 1,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: 'Hei jeg er så glad i Hackerspace, det gir meg livsglede og har stoppet meg flere ganger fra å hoppe utfor elgseterbroen. Jeg har egt ikke mer å si, men må ha litt ekstra linjer tihi',
    mail: 'lisay20.03@hotmail.com',
    instagram: 'lisayuuuuuuuu2.0',
    discord: 'hei på deg din ku',
    github: 'lisayu03',
    linkedin: 'ellnyu',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 2,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 3,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 4,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 5,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 6,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 7,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 8,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 9,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 10,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 11,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
  {
    id: 12,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
    workshop: true,
    printing: true,
    lazercutter: false,
    linuxTerminal: true,
  },
];

export { memberMockData };
