const memberMockData = [
  {
    id: 1,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: 'Hei jeg er så glad i Hackerspace, det gir meg livsglede og har stoppet meg flere ganger fra å hoppe utfor elgseterbroen',
    mail: 'lisay20.03@hotmail.com',
    instagram: 'lisayuuuuuuuu2.0',
    discord: 'hei på deg din ku',
    github: 'lisayu03',
    linkedin:
      'https://www.linkedin.com/authwall?trk=bf&trkInfo=AQHYfT6P9sYR0gAAAZH2C2qIIxaA6fZELF1Hya73jEN85udhyvPoWrVGhYkTvnTq73IlCrWeRtNw0EF5fI9gih73GvGVPC4Xc4V_nULr3UakTjKFQhJwdbmO4416LH34VhIDC1c=&original_referer=&sessionRedirect=https%3A%2F%2Fno.linkedin.com%2Fin%2Fbj%25C3%25B8rn-johan-muri-a5bb2084',
  },
  {
    id: 2,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 3,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 4,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 5,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 6,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 7,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 8,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 9,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
];

/*  const authorMockData = [
    {
      name: 'Michael Jackson',
      initials: 'MJ',
      photoUrl: 'authorMock.jpg',
    },
  ]; */

export { memberMockData };
