const memberMockData = [
  {
    id: 1,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: 'Hei jeg er så glad i Hackerspace, det gir meg livsglede og har stoppet meg flere ganger fra å hoppe utfor elgseterbroen',
    mail: 'lisay20.03@hotmail.com',
    instagram: 'lisayuuuuuuuu2.0',
    discord: 'hei på deg din ku',
    github: 'lisayu03',
    linkedin: 'ellnyu',
  },
  {
    id: 2,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 3,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 4,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 5,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 6,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 7,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 8,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
  {
    id: 9,
    internal: true,
    name: 'Captain Levi',
    photoUrl: 'mock.jpg',
    group: 'DevOps',
    bio: '',
    mail: 'lisay20.03@hotmail.com',
    instagram: '',
    discord: '',
    github: '',
    linkedin: '',
  },
];

/*  const authorMockData = [
    {
      name: 'Michael Jackson',
      initials: 'MJ',
      photoUrl: 'authorMock.jpg',
    },
  ]; */

export { memberMockData };
