name: Code Quality

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
  performance-audit:
    name: Lighthouse Performance Audit
    runs-on: noodlebar
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: true
      NODE_ENV: "production"
      NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
      DB_HOST: "website-next-db-1"
      DB_PORT: "5432"
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: "hackerspace-dev-db"
      S3_HOST: "website-next-s3-1"
      S3_PORT: "9000"
      S3_USER: ${{ secrets.S3_USER }}
      S3_PASSWORD: ${{ secrets.S3_PASSWORD }}
      S3_NAME: "hackerspace-dev-s3"
      LHCI_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Fetch base_ref HEAD
        run: git fetch --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Run Lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          bun add -g @lhci/cli@0.14.x
          lhci autorun
