name: Code Quality

on:
  workflow_dispatch:

jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
  performance-audit:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: true
      NODE_ENV: "production"
      NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
      DB_HOST: "website-next-db-1"
      DB_PORT: "5432"
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: "hackerspace-dev-db"
      S3_HOST: "localhost"
      S3_PORT: "9000"
      S3_USER: "user"
      S3_PASSWORD: "password"
      S3_NAME: "storage"
      FEIDE_CLIENT_ID: ""
      FEIDE_CLIENT_SECRET: ""
      FEIDE_AUTHORIZATION_ENDPOINT: "https://auth.dataporten.no/oauth/authorization"
      FEIDE_TOKEN_ENDPOINT: "https://auth.dataporten.no/oauth/token"
      FEIDE_USERINFO_ENDPOINT: "https://auth.dataporten.no/openid/userinfo"
      FEIDE_EXTENDED_USERINFO_ENDPOINT: "https://api.dataporten.no/userinfo/v1/userinfo"
      MATRIX_SERVER_NAME: ""
      MATRIX_ENDPOINT: "https://matrix.hackerspace-ntnu.no/_synapse/admin"
      MATRIX_SECRET: ""
      LHCI_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
      MATRIX_SHARED_SECRET: " "
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Fetch base_ref HEAD
        run: git fetch --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Run Lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          bun add -g @lhci/cli@0.14.x
          lhci autorun
