name: SSH Deploy Script

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      host:
        required: true
      port:
        required: true
      key:
        required: true
      username:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          key: ${{ secrets.key }}
          username: ${{ secrets.username }}
          script: |
            cd ${GITHUB_REPOSITORY##*/}
            git checkout ${{ inputs.branch }}
            git pull
            docker compose down
            docker compose up -d
