name: SSH Deploy Script

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      path:
        required: true
        type: string
    secrets:
      host:
        required: true
      port:
        required: true
      key:
        required: true
      username:
        required: true

jobs:
  script:
    name: Script
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          key: ${{ secrets.key }}
          username: ${{ secrets.username }}
          script: |
            cd ${{ inputs.path }}
            git checkout ${{ inputs.branch }}
            git pull
            docker compose build app &
            docker compose up db s3 -d
            sleep 5
            wait
            docker compose run --rm app bun run db:migrate
            docker compose run --rm app bun run s3:buckets
            docker compose up -d app
